import Head from 'next/head'

import Link from 'next/link'
import { useEffect } from 'react'
import { useRouter } from 'next/router'



export default function Redirect() {
  const router = useRouter();
  
useEffect(() => {
setTimeout(() =>{
  router.push('https://www.dvaughanportfolio.com')
},2000)
},[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1>Redirecting to <Link href="https://www.dvaughanportfolio.com">my portfolio</Link> found at wwww.dvaughanportfolio.com</h1>
      </main>
    </>
  )
}
